dataset: /home/realvm/CDdata/SYSU-CD
model_name: DINO3CD
model_type: cd
model_arch: SEED_PEFT
peft_method: adapter
mode: train
resume_path: null
exp_name: DINO3CD_DPT_SYSU_adapter
work_dirs: work_dirs
batch_size: 16
num_workers: 8
resize_size: 1
src_size: 256
crop_size: 256
overlap: 128
pred_idx: 0
num_classes: 2
loss_type: ce
loss_weights:
- 1.0
- 1.0
lr: 0.0003
min_lr: 3.0e-05
warmup: 3000
optimizer: adamw
max_epochs: null
max_steps: 15000
early_stop: 80
check_val_every_n_epoch: null
val_check_interval: 1000
val_vis_num: 0
comet: true
save_test_results: test_results
accelerator: gpu
devices: '2'
strategy: ddp_find_unused_parameters_true
precision: 16
